language: node_js
node_js:
  - '0.12'
deploy:
  provider: npm
  api_key:
    secure: ZSwV1/EnPH7A1F+lQuw1jMougvXZdjpksgydOVo86Hd4fPHUUsAajaYyBBRr0suwgnUIxrK6uBsaahcDmBXfNN0dH8wGhpfZHJMRtdFWfD4/5Z0cb/lQ3dg7e/UsAxKI/o29Y5hGoQ/j0wfB1laGwfhZz8jRo2+FFLtyHUgRZsROiD34ntNjs/07Ccnz3ZWAsj8qvY8C3aTD7j43EndUepoMxUXVhwp0PF3GfI0pzh2EqJJY12WY0YYcWeqphSjibudf+UlXmj2OouWNME63Q6b4zKelEKyU+z0rYmD7/1u//40ilqiheWHaoAsg/IoC/a8Pdpx2zMsrQ3IaPrpB+hFESjtFItXU9rWGMlfTWqpENZy9/TDkgxxuAzbBd+u1yuK03Zs66KJqecEo4fdrUywWxj2BNPjdU83S9BMsZhbh7UpnfrNwR4D1CCoL06nfqVG9XDORJOQv6tgkew6DMlW+FIBpJdsIEj24dqf6C+n56xWUuDjjCyIm1YBL13lwFYRVofhxypzep8+irpYjuGdFsgLhHJiJY8PA6yn8nr2LPoaYG1d26cVG1uFZGsjGZQ5PCSf7wrpcBJTR3+gMeVu4KYUsOXSPZwXmXANAfQhsfhMfzAbKLyvHz/2h2eyISE1ABOd9GcdqaZMx1CzLiKC/sPcojtnlq7b0mevcAV0=
  email: wasteland@gmail.com
  on:
    branch: master
